/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalcJurosRouteImport } from './routes/calc-juros'
import { Route as CalcPrimeiroMilhaoRouteImport } from './routes/calc-primeiro-milhao'
import { Route as DicasRouteImport } from './routes/dicas'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcJurosRoute = CalcJurosRouteImport.update({
  id: '/calc-juros',
  path: '/calc-juros',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcPrimeiroMilhaoRoute = CalcPrimeiroMilhaoRouteImport.update({
  id: '/calc-primeiro-milhao',
  path: '/calc-primeiro-milhao',
  getParentRoute: () => rootRouteImport,
} as any)
const DicasRoute = DicasRouteImport.update({
  id: '/dicas',
  path: '/dicas',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calc-juros': typeof CalcJurosRoute
  '/calc-primeiro-milhao': typeof CalcPrimeiroMilhaoRoute
  '/dicas': typeof DicasRoute
  '/metas': typeof MetasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calc-juros': typeof CalcJurosRoute
  '/calc-primeiro-milhao': typeof CalcPrimeiroMilhaoRoute
  '/dicas': typeof DicasRoute
  '/metas': typeof MetasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calc-juros': typeof CalcJurosRoute
  '/calc-primeiro-milhao': typeof CalcPrimeiroMilhaoRoute
  '/dicas': typeof DicasRoute
  '/metas': typeof MetasRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calc-juros'
    | '/calc-primeiro-milhao'
    | '/dicas'
    | '/metas'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calc-juros'
    | '/calc-primeiro-milhao'
    | '/dicas'
    | '/metas'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/calc-juros'
    | '/calc-primeiro-milhao'
    | '/dicas'
    | '/metas'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalcJurosRoute: typeof CalcJurosRoute
  CalcPrimeiroMilhaoRoute: typeof CalcPrimeiroMilhaoRoute
  DicasRoute: typeof DicasRoute
  MetasRoute: typeof MetasRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc-juros': {
      id: '/calc-juros'
      path: '/calc-juros'
      fullPath: '/calc-juros'
      preLoaderRoute: typeof CalcJurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calc-primeiro-milhao': {
      id: '/calc-primeiro-milhao'
      path: '/calc-primeiro-milhao'
      fullPath: '/calc-primeiro-milhao'
      preLoaderRoute: typeof CalcPrimeiroMilhaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicas': {
      id: '/dicas'
      path: '/dicas'
      fullPath: '/dicas'
      preLoaderRoute: typeof DicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalcJurosRoute: CalcJurosRoute,
  CalcPrimeiroMilhaoRoute: CalcPrimeiroMilhaoRoute,
  DicasRoute: DicasRoute,
  MetasRoute: MetasRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
